$(function(){
	var next=$(".next");
	next.click(function(){
		$.fn.fullpage.moveSectionDown();
	});
    $('#dowebok').fullpage({
    	"scrollingSpeed":1200,
    	"navigation":true,
    	//回调函数
    	"afterLoad":function(anchorLink,index){
    		if(index==2){
    			$(".searchImg").css("display","block");
    			if($(".lWords").css("display")=="none"){
    				$(".searchImg").animate({
		    			"right":"31.5%"
		    		},1000,"easeOutBounce",function(){
		    			$(".searchImg").css("display","none");
		    			$(".newSearch").css("display","block");
		    			$(".newSearch").animate({
		    				"top":"23.5%",
		    				"left":"82%",
		    				"width":"30%"
		    			},1000,function(){
		    				$(".bWords").fadeOut(500);
		    				$(".lWords").fadeIn(500);
		    				next.show();
		    			});
		    			$(".shaFas").animate({
		    				"width":"441px"
		    			},1000);
		    		});
    			}else{
    				$(".searchImg").css("display","none");
    			}
    		}
    		if(index==3){
    			next.show();
    		}
    		if(index==4){
    			next.show();
    		}
    		if(index==5){
    			$(".shou").animate({
    				"bottom":"0%"
    			},500,function(){
    				$(".bShuBiao").hide();
    				$(".lShuBiao").show();
    				$(".tiao").animate({
    					"bottom":"60%"
    				},1000);
    				$(".fShaFa").animate({
    					"bottom":"11%"
    				},1000);
    				$(".whiteWords").addClass("words3D");
    				$(".whiteWords").animate({
    					"width":"700px",
    					"left": "5%"
    				},1000,function(){
    					next.show();
    				});
    			});
    		}
    		if(index==6){    			
	    		$(".fShaFa").css("display","none");
    			$(".sixS").css("display","block");
    			if($(".sixS").css("bottom")=="700px"){
    				$(".sixS").animate({
	    				"bottom":"50%",
	    				"left":"38%",
	    				"width":"10%"
	    			},500,function(){
	    				$(".xiangZi,.sixS").animate({
		  					"bottom":"5%"
	    				},1000,function(){
	    					$(".words6-2").fadeIn(1000);
	    					$(".section6").animate({
	    						"background-position-x":"-1100px"
	    					},1000,function(){
	    						$(".kuaitiyuan").animate({
	    							"height":"305px",
	    							"bottom":"15%"
	    						},1000);
	    						$(".women").animate({
	    							"height":"294px",
	    							"left":"75%"
	    						},1000);
	    						$(".words6-2").fadeOut(1000);
	    						$(".door,.ad,.words6,.words6-1").fadeIn(1000);
	    						next.show();
	    					});
	    				});
	    			});
    			}    			
	    	}
	    	if(index==7){
    			$(".starzhe").animate({
    				"background-position-x":0
    			},1500,function(){
    				$(".haoping").fadeIn(1000);
    				next.show();    			 			
    			});    				
    		} 
    		if(index==7){
    			next.show();
    		}
    		if(index==8){
    			$(document).mousemove(function(e){
					var x=e.clientX;
					var y=e.clientY;
					if(y<=350){
						y=350;
					}
					$(".moveshou").css({
						"left":x-$(this).width()/3,
						"top":y-$(this).height()/15
					});		
				});
				$(".kaishi-1").mouseenter(function(){
					$(this).hide();
					$(".kaishi-2").show()
				});
				$(".kaishi-2").mouseleave(function(){
					$(this).hide();
					$(".kaishi-1").show()
				});	
				$(".zaiyici").click(function(){
					$.fn.fullpage.moveTo(1,0);
					window.history.go();
				});				
    		}
    	},
    	 "onLeave":function(index,nextIndex,direction){
    	 	if(index==1){
    	 		next.hide();
    	 	}
	    	if(index==2){
	    		next.hide();
	    		var h=$(window).height();
	    		$(".moveShaFa").css("display","block");
	    		$(".moveShaFa").animate({
	    			"bottom":-(h+80),
	    			"left":"-120%",
	    			"width":"207px"
	    		},1000,function(){
    				$(".bList").fadeOut(500);
    				$(".lList").fadeIn(500);
    				$(".bCar").fadeOut(500);
    				$(".lCar").fadeIn(500);
	    		});	
	    		$(".zhe").css("background-color","white");
	    	}
	    	if(index==3){
	    		next.hide();
    			$(".moveShaFa").css("display","none");
    			$(".moveShaFaX").css("display","block");
    			$(".moveShaFaX").animate({
    				"top":"45%"
    			},1000,function(){    				
    				$(".car,.moveShaFaX").animate({
    					"right":"-100%"
    				},2000,"easeInElastic",function(){
    					$(".words").fadeOut(1000);
    					$(".adress").fadeIn(1000);
    					$(".adressWords").fadeIn(1000);
    					$(".adressTab").fadeIn(1000);
    				});
    			});
	    	}
	    	if(index==4){
    	 		next.hide();
    	 	}
	    	if(index==5){
    	 		next.hide();
    	 		$(".fShaFa").hide();
    	 	}
	    	if(index==6){
    	 		next.hide();    	 		
    	 	}
	    	if(index==7){
    	 		next.hide();
    	 	}
	    },   
    }); 
});



